name: mdevcamp_workshop
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  collection: ^1.19.1
  equatable: ^2.0.7
  faker: ^2.2.0
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  http: ^1.4.0
  json_annotation: ^4.9.0
  netglade_flutter_utils: ^1.1.0
  netglade_utils: ^2.4.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  netglade_analysis: ^16.1.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/breeds.json
    - assets/cats.json
